variable "service-name" {}
variable "cpu" {}
variable "memory" {}
variable "ecr-repository-url" {}
variable "task-exec-role-arn" {}
variable "target-group-arn" {}
variable "subnet-public-a-id" {}
variable "subnet-public-c-id" {}
variable "security-groups" {}
variable "ecs-service-autoscaling-arn" {}
